### PR TITLE
Improve handling of twitter errors

### PR DESCRIPTION
**Pull request by italodeandra**
I was having a problem while handling errors coming from the requests. They were not coming as errors but instead, they were coming on the success response like this:

```
{
    '{"errors": [{...}]}": ''
}
```

Like a really bad formatted JSON. But that wasn't the case when I saw that the library was handling some errors as strings and not differentiating errors from success responses.

I fixed that and some other issues in error handling by creating a new static function and improving the existing one.

### CODE REVIEW

**Comment by italodeandra** [comment]
Fixed the build problem after I created an issue https://github.com/draftbit/twitter-lite/issues/76
The issue can be closed.

**Comment by peterpme** [comment]
Hey @italodeandra sorry for the delay. Thanks so much for this! Has it been fixed? If not, do you mind resolving conflicts and I can merge in?

**Comment by italodeandra** [comment]
Yes, I'm already using my fork on production. I resolved the conflicts, but I'll test it later today (because now you have the types file being copied) so you can merge it. I'll let you know if everything is okay.

**Comment by italodeandra** [comment]
I just tested it and it worked fine, also deployed. Gitignore diff removed. but `package.json` changes is part of the fix, can't remove because it won't be possible to build.

**Pull request merged**
