### PR TITLE
bugfix: issue #78

### LINKED ISSUE #78: getAccessToken outdated and unusable
As can be seen [here](https://github.com/draftbit/twitter-lite/blob/master/twitter.js#L148) the current function only adds `oauth_verifier`. According to the [docs](https://developer.twitter.com/en/docs/basics/authentication/api-reference/access_token), `oauth_token` is also required.
Using this function returns- as expected - this:
`[Object: null prototype] { 'Request token missing': '' }`

### PR DESCRIPTION
**Pull request by T0TProduction**
fixes #78

### CODE REVIEW

**Comment by T0TProduction** [comment]
disclaimer: this has not been tested yet.
According to the docs and the way I created our call without this library to fix the issue in our code, it should be correct usage though.

**Comment by peterpme** [comment]
Thanks so much! Mind testing this :smile: ?

**Comment by T0TProduction** [comment]
tested, found an issue with naming, and fixed it. It now works as intended using the key-value pairs the auth callback provides.

If for some reason apps used to use this though (and it worked? ) it will not be backward compatible because the old code actually used keys that were not the same as the ones the callback provides.

**Comment by T0TProduction** [comment]
> Thanks for the fix! @T0TProduction I believe what Peter was asking was if you could add a test to our testing suite so that we can prevent this bug from happening in the future. Could you attempt to add a test to `test/twitter.test.js` for the specific bug you were facing?

I don't think this can be tested. This is the call based on a user OAuth callback 🤔

**Pull request merged**
